### ISSUE TITLE
Tether has incorrect symbol 

### ISSUE THREAD

**Issue by aph5nt** [noobsmuc/CoinmarketcapClient#12]
for symbol USDT method    var currency = client.GetCurrencyBySymbol(symbol); returns invalid output; check the attachment
 
![usdt](https://user-images.githubusercontent.com/9586677/217560915-a4216320-0d6c-4597-8913-57f20cdb6a06.png)

**Comment by DominikLindemann** [comment]
fixed  in new version 3.0.0
