### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by rinukkusu** [noobsmuc/CoinmarketcapClient#3]
Hi, I'd love to use this client in my project, but I don't really fancy checking out this repository and integrating it into my project or adding it as a submodule. What do you think of creating a NuGet package and pushing it to https://www.nuget.org ?

Thanks in advance,
Max

**Comment by DominikLindemann** [comment]
Hi Max,
there is an existing package in version 2.0.1 on nuget.org
https://www.nuget.org/packages/NoobsMuc.Coinmarketcap.Client/

We update the description with the nuget link. Thanks for your hint

**Comment by rinukkusu** [comment]
Thank you!! 😸
