### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by GerdE73** [noobsmuc/CoinmarketcapClient#6]
hi,
i love your code, thx a lot, and i am using it for several moths without any problems.
Since yersterday it throws the follwing error:
"Newtonsoft.Json.JsonSerializationException: 'Error converting value {null} to type 'System.DateTime'. Path 'data[0].date_added', line 1, position 257.'
Inner Exception
InvalidCastException: Null object cannot be converted to a value type."

I am calling:
  ICoinmarketcapClient m_Sut = new CoinmarketcapClient(APIkey);
  //Limit = 100; 
  var retValue = m_Sut.GetCurrencies(Limit);
  
  what i am doing wrong?
  greetings
    Gerd

**Comment by ramax495** [comment]
PR #7

**Comment by DominikLindemann** [comment]
merged into main
